# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='license_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('name', 'address')]),
        ),
    ]
