# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_inspector', '0002_auto_20151231_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='chi_name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='trimmed_name',
            field=models.CharField(default='Not yet', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('chi_name', 'address')]),
        ),
    ]
